version: "3.8"

services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.9.1
    ports:
      - '0.0.0.0:9200:9200'
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
      - cluster.name=hive
      - script.allowed_types= inline
      - thread_pool.search.queue_size=100000
      - thread_pool.write.queue_size=10000
      - gateway.recover_after_nodes=1
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - es_logs:/usr/share/elasticsearch/logs

  cortex:
    image: thehiveproject/cortex:3.1.1-1
    depends_on:
      - elasticsearch
    ports:
      - "0.0.0.0:9001:9001"
    volumes:
      - ./vol/cortex/application.conf:/etc/cortex/application.conf
      - ./vol/cortex/responders:/opt/cortex/cortex_responders
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp

  # Configurar port e key aqui e não no config file do The Hive
  # https://github.com/TheHive-Project/TheHive/issues/568
  thehive:
    image: thehiveproject/thehive:3.5.1-1
    depends_on:
      - elasticsearch
      - cortex
    restart: unless-stopped
    ports:
      - "0.0.0.0:9000:9000"
    volumes:
      - ./vol/thehive/application.conf:/etc/thehive/application.conf
    command:
      --cortex-port 9001
      --cortex-key "p5heJ+iuOAs9CEqXPc1JfXGrPvXbeWBl"   

  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx:1.19.5
    depends_on:
      - thehive
      - cortex
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./vol/nginx:/etc/nginx/conf.d
      - ./vol/ssl:/etc/ssl
    restart: on-failure

volumes:
  es_data:
    driver: local
  es_logs:
    driver: local 
